src/Entity/ContratVie.php
<?php

namespace App\Entity;
use App\Entity\Client;

use App\Repository\ContratVieRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;


#[ORM\Entity(repositoryClass: ContratVieRepository::class)]
class ContratVie extends ContratAssurance
{


    #[ORM\Column(type: Types::DATE_MUTABLE)]
    #[Assert\NotBlank(message: 'La date du debut est obligatoire')]

    private ?\DateTimeInterface $Date_debut = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    #[Assert\NotBlank(message: 'La date de la fin est obligatoire')]

    private ?\DateTimeInterface $Date_fin = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: 'Le champs détail est obligatoire')]

    private ?string $Description = null;

    #[ORM\Column(length: 20)]
    #[Assert\NotBlank(message: 'Votre matricule est obligatoire')]

    private ?string $MatriculeAgent = null;

    #[ORM\Column(length: 20)]
    private ?string $Prix = null;


    public function getDateDebut(): ?\DateTimeInterface
    {

        return $this->Date_debut;
    }

    public function setDateDebut(\DateTimeInterface $Date_debut): static
    {
        $this->Date_debut = $Date_debut;

        return $this;
    }

    public function getDateFin(): ?\DateTimeInterface
    {
        return $this->Date_fin;
    }

    public function setDateFin(\DateTimeInterface $Date_fin): static
    {
        $this->Date_fin = $Date_fin;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(string $Description): static
    {
        $this->Description = $Description;

        return $this;
    }

    public function getMatriculeAgent(): ?string
    {
        return $this->MatriculeAgent;
    }

    public function setMatriculeAgent(string $MatriculeAgent): static
    {
        $this->MatriculeAgent = $MatriculeAgent;

        return $this;
    }

    public function getPrix(): ?string
    {
        return $this->Prix;
    }

    public function setPrix(string $Prix): static
    {
        $this->Prix = $Prix;

        return $this;
    }
}

src/Entity/LifeRequest.php
<?php

namespace App\Entity;

use App\Repository\LifeRequestRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: LifeRequestRepository::class)]
class LifeRequest extends InsuranceRequest
{
   #[ORM\Column(length: 20)]
   #[Assert\NotBlank(message: 'Veuillez entrer votre âge.')]
   #[Assert\Length(
       min: 2,
       max: 3, // Assuming age is a number with at most 3 digits
       minMessage: 'L\'âge doit comporter au moins {{ limit }} caractères.',
       maxMessage: 'L\'âge ne peut pas dépasser {{ limit }} caractères.'
   )]
   #[Assert\GreaterThan(
       value: 18,
       message: 'L\'âge doit être supérieur à 18 ans.'
   )]

    private ?string $Age = null;

    #[ORM\Column(length: 50)]
    #[Assert\NotBlank(message: 'Veuillez mentionner si vous avez une maladie chronique.')]

    private ?string $chron_disease = null;

   #[Assert\NotBlank(message: 'Veuillez mentionner si vous avez affectué une operation.')]

    #[ORM\Column(length: 50)]
    private ?string $surgery = null;

   #[Assert\NotBlank(message: 'Veuillez mentionner votre etat civil.')]
    #[ORM\Column(length: 20)]
    private ?string $civil_status = null;


    #[ORM\Column(length: 30)]
    #[Assert\NotBlank(message: 'Veuillez mentionner votre profession.')]

    private ?string $occupation = null;

    #[ORM\Column(length: 100, nullable: true)]

    private ?string $chron_disease_description = null;

    public function getAge(): ?string
    {
        return $this->Age;
    }

    public function setAge(string $Age): static
    {
        $this->Age = $Age;

        return $this;
    }

    public function getChronDisease(): ?string
    {
        return $this->chron_disease;
    }

    public function setChronDisease(string $chron_disease): static
    {
        $this->chron_disease = $chron_disease;

        return $this;
    }

    public function getSurgery(): ?string
    {
        return $this->surgery;
    }

    public function setSurgery(string $surgery): static
    {
        $this->surgery = $surgery;

        return $this;
    }

    public function getCivilStatus(): ?string
    {
        return $this->civil_status;
    }

    public function setCivilStatus(string $civil_status): static
    {
        $this->civil_status = $civil_status;

        return $this;
    }

    public function getOccupation(): ?string
    {
        return $this->occupation;
    }

    public function setOccupation(string $occupation): static
    {
        $this->occupation = $occupation;

        return $this;
    }

    public function getChronDiseaseDescription(): ?string
    {
        return $this->chron_disease_description;
    }

    public function setChronDiseaseDescription(?string $chron_disease_description): static
    {
        $this->chron_disease_description = $chron_disease_description;

        return $this;
    }
}

src/Form/ContratVieType.php
<?php

namespace App\Form;
use App\Entity\LifeRequest;

use App\Entity\ContratVie;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;

class ContratVieType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('Date_debut')
            ->add('Date_fin')
            ->add('Description')
            ->add('MatriculeAgent')
            ->add('Prix')
            ->add('request', EntityType::class, [
                           'class' => LifeRequest::class,
                           'choice_label' => 'id',
                       ]);
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => ContratVie::class,
        ]);
    }
}

src/Controller/ContratVieController.php
<?php

namespace App\Controller;
use App\Repository\LifeRequestRepository;
use App\Entity\LifeRequest;
use App\Service\PdfService;
use App\Service\TwilioService;
use MercurySeries\FlashyBundle\FlashyNotifier;
use App\Entity\ContratVie;
use App\Form\ContratVieType;
use App\Repository\ContratVieRepository;
use Doctrine\ORM\EntityManagerInterface;
use Dompdf\Dompdf;
use Dompdf\Options;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\Mailer\MailerInterface;
use Symfony\Component\Mime\Email;

#[Route('/contrat/vie')]
class ContratVieController extends AbstractController
{
 private $twilioService;


        public function __construct(TwilioService $twilioService)
        {
            $this->twilioService = $twilioService;
        }
    
    #[Route('/', name: 'app_contrat_vie_index', methods: ['GET'])]
    public function index(ContratVieRepository $contratVieRepository): Response
    {
        return $this->render('contrat_vie/index.html.twig', [
            'contrat_vies' => $contratVieRepository->findAll(),
        ]);
    }
    #[Route('/contrat/UserLife', name: 'app_contrat_vie_user', methods: ['GET'])]
    public function abc(ContratVieRepository $contratVieRepository): Response
    {
        return $this->render('life_request/showContrat.html.twig', [
            'contrat_vie' => $contratVieRepository->findAll()[count($contratVieRepository->findAll())-1],
        ]);
    }

    #[Route('/New_ContratVie', name: 'app_contrat_vie_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $contratVie = new ContratVie();
        $form = $this->createForm(ContratVieType::class, $contratVie);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($contratVie);
            $entityManager->flush();

            return $this->redirectToRoute('app_contrat_vie_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('contrat_vie/new.html.twig', [
            'contrat_vie' => $contratVie,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_contrat_vie_show', methods: ['GET'])]
    public function show(ContratVie $contratVie): Response
    {
        return $this->render('contrat_vie/show.html.twig', [
            'contrat_vie' => $contratVie,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_contrat_vie_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, ContratVie $contratVie, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(ContratVieType::class, $contratVie);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_contrat_vie_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('contrat_vie/edit.html.twig', [
            'contrat_vie' => $contratVie,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_contrat_vie_delete', methods: ['POST'])]
    public function delete(Request $request, ContratVie $contratVie, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$contratVie->getId(), $request->request->get('_token'))) {
            $entityManager->remove($contratVie);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_contrat_vie_index', [], Response::HTTP_SEE_OTHER);
    }

    #[Route('/showDemandes_vie', name: 'app_contrat_vie_show_in_contrat', methods: ['GET'])]
        public function showDemandes_vie(PaginatorInterface $paginator, LifeRequestRepository $lifeRequestRepository,  Request $request): Response
        {
             $pagination = $paginator->paginate(
              $lifeRequestRepository->findAll(),
             $request->query->getInt('page', 1),5 );
                return $this->render('contrat_vie/showDemandes.html.twig', [
                                        'life_requests' => $pagination,
                                      ]);

        }

         #[Route('/{id}/New_ContratVie', name: 'app_contrat_vie_newId', methods: ['GET', 'POST'])]
            public function newId(FlashyNotifier $flashy, Request $request, EntityManagerInterface $entityManager, LifeRequestRepository $lifeRequestRepository, $id): Response
            {
                $contratVie = new ContratVie();
                $form = $this->createForm(ContratVieType::class, $contratVie);
                $form->handleRequest($request);
                $data= $lifeRequestRepository->find($id) ;

                if ($form->isSubmitted() && $form->isValid()) {
                    $entityManager->persist($contratVie);
                    $entityManager->flush();
                        $demande = $contratVie->getRequest();
                        $flashy->success('Le contrat a été ajouté avec succes !');

                        if ($demande) {
                            $demande->setStatus('Accepter');
                            $entityManager->flush();
                        }
                     //    $this->twilioService->sendSms(
                       //                    +21652021389',
                         //                  'Votre contrat est pret. Veuillez terminer la procédure du paiement'
                           //                       );
                    return $this->redirectToRoute('app_contrat_vie_index', [], Response::HTTP_SEE_OTHER);
                }

                return $this->renderForm('contrat_vie/new.html.twig', [
                    'contrat_vie' => $contratVie,
                    'form' => $form,
                    'life_request' => $data
                ]);
            }
            #[Route('/pdf_vie/{id}', name: 'contrat_vie.pdf')]
                public function generatePdfPersonne(MailerInterface $mailer,ContratVie $contratVie = null, PdfService $pdf) {
                    $html = $this->render('contrat_vie/showPdf.html.twig', ['contrat_vie' => $contratVie]);
                    $pdfOptions = new Options();
                    $pdfOptions->set('defaultFont','Arial');
                    $pdfOptions->setIsRemoteEnabled(true);
                    $pdfOptions->set('isHtml5ParserEnabled',true);
                    $dompdf = new Dompdf($pdfOptions);
                    $dompdf->loadHtml($html);
                    $dompdf->setPaper('A4','portrait');
                    $dompdf->render();
                    $email = (new Email())
                    ->from('oussemaa782@gmail.com')
                    ->to("yasmine.said2001@gmail.com")
                    ->subject("Contrat")
                    ->text("hello , this is your contract")
                    ->attach($dompdf->output(),"contrat habitat");
            
                        $mailer->send($email);
                    return new RedirectResponse($this->generateUrl('app_contrat_vie_show', ['id' => $contratVie->getId()]));

                }

            #[Route('/refuser-demande-vie/{id}', name: 'refuser_demande_vie')]
            public function refuserDemande($id, EntityManagerInterface $entityManager, LifeRequestRepository $lifeRequestRepository): Response
            {
                $demande = $lifeRequestRepository->find($id);

                if (!$demande) {
                    throw $this->createNotFoundException('Demande non trouvée');
                }

                $demande->setStatus('Refusée');
                $entityManager->flush();

                    return $this->redirectToRoute('app_contrat_vie_show_in_contrat', [], Response::HTTP_SEE_OTHER);
            }

}

templates/contrat_vie/_delete_form.html.twig
<form method="post" action="{{ path('app_contrat_vie_delete', {'id': contrat_vie.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ contrat_vie.id) }}">
    <button class="btn">Delete</button>
</form>

templates/contrat_vie/_form.html.twig
<body>
    <div class="container">
               <section class="section register min-vh-100 d-flex flex-column align-items-center justify-content-center py-4">
                   <div class="row">
                       <div class="col-md-6">
                           <div class="card mb-3">
                               <div class="card-body">
                                   <h5 class="card-title">Demande assurance {{ contrat_vie.id }}</h5>
                                   <table class="table table-striped">
   
                                       <thead>
   
    <tr>
                   <th>Id</th>
                   <td>{{ life_request.id}}</td>
   
               </tr>
               <tr>
                   <th>Date demande</th>
                   <td>{{ life_request.dateRequest ? life_request.dateRequest|date('Y-m-d') : '' }}</td>
   
               </tr>
               <tr>
                   <th>Type assurance</th>
                   <td>{{ life_request.typeInsurance }}</td>
               </tr>
   
               <tr>
                   <th>Age</th>
                   <td>{{ life_request.Age }}</td>
               </tr>
               <tr>
                   <th>Maladie chronique</th>
                   <td>{{ life_request.chronDisease }}</td>
               </tr>
   
                              <tr>
                                           <th>Operation</th>
                   <td>{{ life_request.surgery }}</td>
                                       </tr>
                                           <tr>
                                 <th>Etat civil</th>
                   <td>{{ life_request.civilStatus }}</td>
                                    </tr>
                       <tr>
                                                                                                  <th>Profesion</th>
                                      <td>{{ life_request.occupation }}</td>
                                                                                              </tr>
            </thead>
                                           </table>
                                       </div>
                                   </div>
                               </div>
                               <div class="col-md-6">
                                   <div class="card mb-3">
                                       <div class="card-body">
                                           <h5 class="card-title">Contrat</h5>
   
   
   
   {{ form_start(form, {'attr': {'class': 'row g-3 needs-validation', 'novalidate': 'novalidate', 'style': 'max-width: 400px;'}}) }}
   {% if form_errors(form) %}
   
               <div class="alert alert-danger">
                   <ul>
                       {% for error in form_errors(form) %}
                           <li>{{ error.message }}</li>
                       {% endfor %}
                   </ul>
               </div>
           {% endif %}
   
   
   
       <div class="col-6">
               <label for="Date_debut" class="form-label">Date debut du contrat</label>
               {{ form_widget(form.Date_debut, {'attr': {'class': 'form-control', 'id': 'Date_debut'}}) }}
               {% if form_errors(form.Date_debut) %}
                          <div class="alert alert-danger">
                              {{ form_errors(form.Date_debut) }}
                          </div>
               {% endif %}
           </div>
           <div class="col-6">
                   <label for="Date_fin" class="form-label">Date fin du contrat</label>
                   {{ form_widget(form.Date_fin, {'attr': {'class': 'form-control', 'id': 'Modele'}}) }}
                   {% if form_errors(form.Date_fin) %}
                                                           <div class="alert alert-danger">
                                                               {{ form_errors(form.Date_fin) }}
                                                           </div>
                                                       {% endif %}
               </div>
        <div class="col-12">
                <label for="Description" class="form-label">Détail du contrat</label>
                {{ form_widget(form.Description, {'attr': {'class': 'form-control', 'id': 'Description'}}) }}
                {% if form_errors(form.Description) %}
                                                        <div class="alert alert-danger">
                                                            {{ form_errors(form.Description) }}
                                                        </div>
                                                    {% endif %}
            </div>
   
            <div class="col-12">
                                 <label for="Prix" class="form-label">Prix du contrat</label>
                                 {{ form_widget(form.Prix, {'attr': {'class': 'form-control', 'id': 'MatriculeAgent'}}) }}
                                 {% if form_errors(form.Prix) %}
                                                                         <div class="alert alert-danger">
                                                                             {{ form_errors(form.Prix) }}
                                                                         </div>
                                                                     {% endif %}
                             </div>
       <div class="col-12">
               <label for="MatriculeAgent" class="form-label">Matricule de l'agent</label>
               {{ form_widget(form.MatriculeAgent, {'attr': {'class': 'form-control', 'id': 'MatriculeAgent'}}) }}
               {% if form_errors(form.MatriculeAgent) %}
                                                       <div class="alert alert-danger">
                                                           {{ form_errors(form.MatriculeAgent) }}
                                                       </div>
                                                   {% endif %}
           </div>
   
   
   
       <div class="col-12">
   
       <button class="btn btn-primary w-100">{{ button_label|default('Save') }}</button>
       </div>
           <div class="col-12">
       <a href="{{ path('app_contrat_vie_index') }}" class="btn btn-primary w-100">back to list</a>
   
       </div>
   
   
   {{ form_end(form) }}
   </div>
                           </div>
                       </div>
                   </div>
               </section>
           </div>
       </main>
   
   
   </body>

templates/contrat_vie/edit.html.twig
{% extends 'admin/index.html.twig' %}

{% block title %}Edit ContratVie{% endblock %}

{% block profile %}
    <h1>Edit ContratVie</h1>

<div class="col-md-7">
                                <div class="card mb-3">
                                    <div class="card-body">
                                        <h5 class="card-title">Formulaire</h5>



{{ form_start(form, {'attr': {'class': 'row g-3 needs-validation', 'novalidate': 'novalidate', 'style': 'max-width: 400px;'}}) }}
{% if form_errors(form) %}

            <div class="alert alert-danger">
                <ul>
                    {% for error in form_errors(form) %}
                        <li>{{ error.message }}</li>
                    {% endfor %}
                </ul>
            </div>
        {% endif %}



    <div class="col-6">
            <label for="Date_debut" class="form-label">Date debut du contrat</label>
            {{ form_widget(form.Date_debut, {'attr': {'class': 'form-control', 'id': 'Date_debut'}}) }}
            {% if form_errors(form.Date_debut) %}
                       <div class="alert alert-danger">
                           {{ form_errors(form.Date_debut) }}
                       </div>
            {% endif %}
        </div>
        <div class="col-6">
                <label for="Date_fin" class="form-label">Date fin du contrat</label>
                {{ form_widget(form.Date_fin, {'attr': {'class': 'form-control', 'id': 'Modele'}}) }}
                {% if form_errors(form.Date_fin) %}
                                                        <div class="alert alert-danger">
                                                            {{ form_errors(form.Date_fin) }}
                                                        </div>
                                                    {% endif %}
            </div>
     <div class="col-12">
             <label for="Description" class="form-label">Détail du contrat</label>
             {{ form_widget(form.Description, {'attr': {'class': 'form-control', 'id': 'Description'}}) }}
             {% if form_errors(form.Description) %}
                                                     <div class="alert alert-danger">
                                                         {{ form_errors(form.Description) }}
                                                     </div>
                                                 {% endif %}
         </div>
    <div class="col-12">
            <label for="MatriculeAgent" class="form-label">Matricule de l'agent</label>
            {{ form_widget(form.MatriculeAgent, {'attr': {'class': 'form-control', 'id': 'MatriculeAgent'}}) }}
            {% if form_errors(form.MatriculeAgent) %}
                                                    <div class="alert alert-danger">
                                                        {{ form_errors(form.MatriculeAgent) }}
                                                    </div>
                                                {% endif %}
        </div>



    <div class="col-12">

    <button class="btn btn-primary w-100">{{ button_label|default('Update') }}</button>
    </div>
        <div class="col-12">
    <a href="{{ path('app_contrat_vie_index') }}" class="btn btn-primary w-100">back to list</a>

    </div>


{{ form_end(form) }}
</div>
                        </div>
                    </div>
    <a href="{{ path('app_contrat_vie_index') }}">back to list</a>

    {{ include('contrat_vie/_delete_form.html.twig') }}
{% endblock %}

templates/contrat_vie/new.html.twig
{% extends 'admin/index.html.twig' %}

{% block title %}New ContratVie{% endblock %}

{% block profile %}
    <div class="section-title">
        <h2>Ajouter un nouveau contrat maladie</h2>
     </div>

    {{ include('contrat_vie/_form.html.twig') }}

    <a href="{{ path('app_contrat_vie_index') }}">back to list</a>
{% endblock %}

templates/contrat_vie/showDemandes.html.twig
{% extends 'admin/index.html.twig' %}

{% block title %}LifeRequest index{% endblock %}

{% block profile %}


<section >

<div class="container mt-4">
<div class="row justify-content-center">
    <div class="col-md-12">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title mb-4">Demandes Maladie</h5>
                <div class="d-flex justify-content-between align-items-center mb-3">
                    <div class="input-group" style="width: 40%;">
                        <input class="form-control border-end-0 border rounded-pill py-2" type="search" id="example-search-input" style="font-size: 0.875rem;" placeholder="Search...">
                        <span class="input-group-append">
                            <button class="btn btn-outline-secondary border-bottom-0 border rounded-pill py-2" type="button" id="searchButton" style="font-size: 0.875rem;">Search</button>
                        </span>
                    </div>
                </div> 
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th>Id</th>
                                <th>Date</th>
                                <th>Type assurance</th>
                                <th>Status</th>
                                <th>Age</th>
                                <th>Maladie chronique</th>
                                <th>Operation</th>
                                <th>Etat civil</th>
                                <th>Profession</th>
                                <th>actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for life_request in life_requests %}
                    <tr class="requestVehicule-row">
                                <td>{{ life_request.id }}</td>
                                <td>{{ life_request.dateRequest ? life_request.dateRequest|date('Y-m-d') : '' }}</td>
                                <td>{{ life_request.typeInsurance }}</td>
                                <td>{{ life_request.status }}</td>
                                <td>{{ life_request.Age }}</td>
                                <td>{{ life_request.chronDisease }}</td>
                                <td>{{ life_request.surgery }}</td>
                                <td>{{ life_request.civilStatus }}</td>
                                <td>{{ life_request.occupation }}</td>
                              <td>
                                  {% if life_request.status == 'Accepter' %}
                                      <button type="button" class="btn btn-success rounded-pill" disabled>Accepter</button>
                                  {% elseif life_request.status == 'Refusée' %}
                                      <button type="button" class="btn btn-danger refuseButton" disabled>Refuser</button>
                                  {% else %}
                                      <button type="button" onclick="window.location='{{ path('app_contrat_vie_newId',  {'id': life_request.id}) }}'" class="btn btn-success rounded-pill">Valider</button>
                                      <form class="refuse-demande-form" action="{{ path('refuser_demande_vie', {'id': life_request.id}) }}" method="post">
                                          <input type="hidden" name="_method" value="POST">
                                          <button type="submit" class="btn btn-danger refuseButton">Refuser</button>
                                      </form>
                                  {% endif %}
                              </td>
                            </tr>
                            {% else %}
                            <tr>
                                <td colspan="10">no records found</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
               <nav aria-label="Page navigation example">
                        <ul class="pagination justify-content-center">
                        {{ knp_pagination_render(life_requests) }}
                           </ul>
                       </nav>
                       <br>
                       <br>
                       <br>
                       <br>
                </div>
            </div>
        </div>
    </div>
</section>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@10"></script>
<script>
    // Sélectionnez tous les boutons "Refuser" par leur classe
    var refuseButtons = document.querySelectorAll('.refuseButton');

    // Ajoutez un écouteur d'événements à chaque bouton "Refuser"
    refuseButtons.forEach(function(button) {
        button.addEventListener('click', function(event) {
            event.preventDefault();

            Swal.fire({
                title: 'Êtes-vous sûr?',
                text: "Vous ne pourrez pas revenir en arrière!",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Oui, refuser!'
            }).then((result) => {
                if (result.isConfirmed) {
                    // Trouvez le formulaire parent et soumettez-le
                    var form = button.closest('.refuse-demande-form');
                    form.submit();
                }
            });
        });
    });
</script>
<script>
$(document).ready(function () {
            $('#searchButton').click(function () {
                var searchQuery = $('#example-search-input').val().toLowerCase();
                var noRequestVehiculeRow = $('#noUserRequestVehiculeRow');

                // Loop through each user row and show/hide based on the search query
                $('.requestVehicule-row').each(function () {
                    var userRowText = $(this).text().toLowerCase();

                    // If the search query is found in the user row, show it; otherwise, hide it
                    $(this).toggle(userRowText.includes(searchQuery));
                });

                noRequestVehiculeRow.toggle($('.requestVehicule-row:visible').length === 0);
            });
        });
</script>
{% endblock %}