src/Entity/Prescription.php
<?php

namespace App\Entity;

use App\Repository\PrescriptionRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PrescriptionRepository::class)]
class Prescription
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private $datePrescription ;

    public function __construct()
    {
        $this->datePrescription = new \DateTime();
    }
    #[ORM\Column(type: Types::TEXT)]
    #[Assert\NotBlank(message: 'Please enter the status of the medications needed.')]
    private ?string $medications = null;

    #[ORM\Column(length: 20)]
    #[Assert\NotBlank(message: 'Please enter the status of the Prescription.')]
    #[Assert\Choice(choices: ["processed", "unprocessed"])]
    private ?string $statusPrescription = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $additionalNotes = null;

    #[ORM\Column(nullable: true)]
    private ?int $validityDuration = null;

    #[ORM\ManyToOne(inversedBy: 'prescriptionUser')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $userCIN = null;

    public function getdatePrescription(): ?\DateTimeInterface
    {
        return $this->datePrescription;
    }

    public function setdatePrescription(\DateTimeInterface $datePrescription): static
    {
        $this->datePrescription = $datePrescription;

        return $this;
    }


    public function getMedications(): ?string
    {
        return $this->medications;
    }

    public function setMedications(string $medications): static
    {
        $this->medications = $medications;

        return $this;
    }

    public function getStatusPrescription(): ?string
    {
        return $this->statusPrescription;
    }

    public function setStatusPrescription(string $statusPrescription): static
    {
        $this->statusPrescription = $statusPrescription;

        return $this;
    }

    public function getAdditionalNotes(): ?string
    {
        return $this->additionalNotes;
    }

    public function setAdditionalNotes(?string $additionalNotes): static
    {
        $this->additionalNotes = $additionalNotes;

        return $this;
    }

    public function getValidityDuration(): ?int
    {
        return $this->validityDuration;
    }

    public function setValidityDuration(?int $validityDuration): static
    {
        $this->validityDuration = $validityDuration;

        return $this;
    }

    public function getUserCIN(): ?User
    {
        return $this->userCIN;
    }

    public function setUserCIN(?User $userCIN): static
    {
        $this->userCIN = $userCIN;

        return $this;
    }


}

src/Entity/Remorqueur.php
<?php

namespace App\Entity;

use App\Repository\RemorqueurRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: RemorqueurRepository::class)]
class Remorqueur
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: 'veuillez fournir le prenom du remorqueur')]
    private ?string $FirstName = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: 'veuillez fournir le nom du remorquer')]
    private ?string $LastName = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: 'veuillez fournir le numéro du remorquer')]

    private ?string $PhoneNumber = null;

    #[ORM\Column]
    #[Assert\NotBlank(message: 'veuillez fournir la lattitude du remorquer')]

    private ?float $lattitude = null;

    #[ORM\Column]
    #[Assert\NotBlank(message: 'veuillez fournir longitude du remorquer')]

    private ?float $longuitude = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstName(): ?string
    {
        return $this->FirstName;
    }

    public function setFirstName(string $FirstName): static
    {
        $this->FirstName = $FirstName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->LastName;
    }

    public function setLastName(string $LastName): static
    {
        $this->LastName = $LastName;

        return $this;
    }

    public function getPhoneNumber(): ?string
    {
        return $this->PhoneNumber;
    }

    public function setPhoneNumber(string $PhoneNumber): static
    {
        $this->PhoneNumber = $PhoneNumber;

        return $this;
    }

    public function getLattitude(): ?float
    {
        return $this->lattitude;
    }

    public function setLattitude(float $lattitude): static
    {
        $this->lattitude = $lattitude;

        return $this;
    }

    public function getLonguitude(): ?float
    {
        return $this->longuitude;
    }

    public function setLonguitude(float $longuitude): static
    {
        $this->longuitude = $longuitude;

        return $this;
    }
}

src/Form/PrescriptionType.php
<?php

namespace App\Form;

use App\Entity\Prescription;
use App\Entity\User;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PrescriptionType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('datePrescription')
            ->add('medications')
            ->add('statusPrescription')
            ->add('additionalNotes')
            ->add('validityDuration')
            ->add('userCIN', EntityType::class, [
                'class' => User::class,
                'choice_label' => 'cin',
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Prescription::class,
        ]);
    }
}

src/Controller/PrescriptionController.php
<?php

namespace App\Controller;

use App\Entity\Prescription;
use App\Form\PrescriptionType;
use App\Repository\PrescriptionRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Dompdf\Dompdf;
use App\Service\DrugService;


#[Route('/prescription')]
class PrescriptionController extends AbstractController
{
    #[Route('/', name: 'app_prescription_index', methods: ['GET'])]
    public function index(PrescriptionRepository $prescriptionRepository): Response
    {
        return $this->render('prescription/index.html.twig', [
            'prescriptions' => $prescriptionRepository->findAll(),
        ]);
    }

    #[Route('/new/pres', name: 'app_prescription_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $prescription = new Prescription();
        $form = $this->createForm(PrescriptionType::class, $prescription);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($prescription);
            $entityManager->flush();

            return $this->redirectToRoute('app_prescription_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('prescription/new.html.twig', [
            'prescription' => $prescription,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_prescription_show', methods: ['GET'])]
    public function show(Prescription $prescription): Response
    {
        return $this->render('prescription/show.html.twig', [
            'prescription' => $prescription,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_prescription_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Prescription $prescription, EntityManagerInterface $entityManager): Response
    {
        $originalData = clone $prescription;
        $form = $this->createForm(PrescriptionType::class, $prescription);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            // Compute changes
            $uow = $entityManager->getUnitOfWork();
            $uow->computeChangeSets(); // Calculate the changes

            $changes = $uow->getEntityChangeSet($prescription);

            if (count($changes) > 0) {
                // If there are changes, flush and show success message
                $entityManager->flush();
                $this->addFlash('success', 'Prescription updated successfully.');
            } else {
                // If no changes, show warning message
                $this->addFlash('warning', 'No changes have been made,Please update before submitting.');
            }

            return $this->redirectToRoute('app_prescription_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('prescription/edit.html.twig', [
            'prescription' => $prescription,
            'form' => $form,
        ]);
    }


    #[Route('/{id}', name: 'app_prescription_delete', methods: ['POST'])]
    public function delete(Request $request, Prescription $prescription, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete' . $prescription->getId(), $request->request->get('_token'))) {
            $entityManager->remove($prescription);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_prescription_index', [], Response::HTTP_SEE_OTHER);
    }

    #[Route('/prescription/{id}/export-pdf', name: 'prescription_export_pdf')]
    public function exportToPdfAction(Prescription $prescription)
    {
        $data = [
            'datePrescription' => $prescription->getDatePrescription()->format('Y-m-d'),
            'medications' => $prescription->getMedications(),
            'statusPrescription' => $prescription->getStatusPrescription(),
            'additionalNotes' => $prescription->getAdditionalNotes(),
            'validityDuration' => $prescription->getValidityDuration(),
            'userCIN' => $prescription->getUserCIN(),
        ];

        $html = $this->renderView('prescription/pdf_template.html.twig', [
            'prescription' => $data,
        ]);

        $dompdf = new Dompdf();
        $dompdf->loadHtml($html);


        $dompdf->render();


        return new Response($dompdf->output(), Response::HTTP_OK, [
            'Content-Type' => 'application/pdf',
            'Content-Disposition' => 'attachment; filename="prescription_' . $prescription->getId() . '.pdf"',
        ]);
    }


    #[Route('/drug-search/pres', name: 'drug_search')]
    public function searchDrug(Request $request, DrugService $drugService , PrescriptionRepository $prescriptionRepository): Response
    {

        $drugName = $request->query->get('drugName');
        $prescriptionId = $request->query->get('prescriptionId');
        $prescription = null;
        $drugDetails = null;

        if ($prescriptionId) {
            $prescription = $prescriptionRepository->find($prescriptionId);
        }
        if ($drugName) {
            $drugDetails = $drugService->searchDrug($drugName);
        }

        // Render the same `show.html.twig` with additional `drugDetails` or a separate template as needed
        return $this->render('prescription/show.html.twig', [
            'drugDetails' => $drugDetails,
            // Pass other required variables for the `show.html.twig` template
        ]);
    }
}

templates/prescription/_delete_form.html.twig
<form method="post" action="{{ path('app_prescription_delete', {'id': prescription.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ prescription.id) }}">
    <button class="btn">Delete</button>
</form>

templates/prescription/_form.html.twig
<body>
<main>
    <div class="container">

        <section class="section register min-vh-100 d-flex flex-column align-items-center justify-content-center py-4">
            <div class="card mb-3">

                <div class="card-body">


                    {{ form_start(form, {'attr': {'class': 'row g-3 needs-validation', 'novalidate': 'novalidate'}}) }}
                    {% if form_errors(form) %}

                        <div class="alert alert-danger">
                            <ul>
                                {% for error in form_errors(form) %}
                                    <li>{{ error.message }}</li>
                                {% endfor %}
                            </ul>
                        </div>
                    {% endif %}
                    <div class="col-12">
                        <label for="datePrescription" class="form-label">Date Prescription </label>
                        {{ form_widget(form.datePrescription, {'attr': {'class': 'form-control', 'id': 'datePrescription'}}) }}
                        {% if form_errors(form.datePrescription) %}
                            <div class="alert alert-danger">
                                {{ form_errors(form.datePrescription) }}
                            </div>
                        {% endif %}
                    </div>


                    <div class="col-12">
                        <label for="medications" class="form-label">Medications</label>
                        {{ form_widget(form.medications, {'attr': {'class': 'form-control', 'id': 'medications'}}) }}
                        {% if form_errors(form.medications) %}
                            <div class="alert alert-danger">
                                {{ form_errors(form.medications) }}
                            </div>
                        {% endif %}
                    </div>


                    <div class="col-12">
                        <label for="statusPrescription" class="form-label">Status Prescription</label>
                        {{ form_widget(form.statusPrescription, {'attr': {'class': 'form-control', 'id': 'statusPrescription'}}) }}
                        {% if form_errors(form.statusPrescription) %}
                            <div class="alert alert-danger">
                                {{ form_errors(form.statusPrescription) }}
                            </div>
                        {% endif %}
                    </div>
                    <div class="col-12">
                        <label for="additionalNotes" class="form-label"> Additional Notes </label>
                        {{ form_widget(form.additionalNotes, {'attr': {'class': 'form-control', 'id': 'additionalNotes'}}) }}
                        {% if form_errors(form.additionalNotes) %}
                            <div class="alert alert-danger">
                                {{ form_errors(form.additionalNotes) }}
                            </div>
                        {% endif %}
                    </div>
                    <div class="col-12">
                        <label for="validityDuration" class="form-label">Validity Duration</label>
                        {{ form_widget(form.validityDuration, {'attr': {'class': 'form-control', 'id': 'validityDuration'}}) }}
                        {% if form_errors(form.validityDuration) %}
                            <div class="alert alert-danger">
                                {{ form_errors(form.validityDuration) }}
                            </div>
                        {% endif %}
                    </div>
                    <div class="col-12">
                        <label for="userCIN" class="form-label">Client CIN</label>
                        {{ form_widget(form.userCIN, {'attr': {'class': 'form-control', 'id': 'userCIN'}}) }}
                        {% if form_errors(form.userCIN) %}
                            <div class="alert alert-danger">
                                {{ form_errors(form.userCIN) }}
                            </div>
                        {% endif %}
                    </div>


                    <div class="col-12">

                        <button class="btn btn-primary w-100">{{ button_label|default('Save') }}</button>
                    </div>
                    <div class="col-12">
                        <a href="{{ path('app_sinister_life_index') }}" class="btn btn-primary w-100">back to list</a>

                    </div>


                    {{ form_end(form) }}
                </div>
            </div>
        </section>

    </div>
</main><!-- End #main -->



</body>

templates/prescription/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Prescription{% endblock %}

{% block body %}
    <h1>Edit Prescription</h1>

    {{ include('prescription/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_prescription_index') }}">back to list</a>

    {{ include('prescription/_delete_form.html.twig') }}
{% endblock %}

templates/prescription/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Prescription index{% endblock %}

{% block body %}
    {% for message in app.flashes('success') %}
        <div class="alert alert-success">{{ message }}</div>
    {% endfor %}

    {% for message in app.flashes('warning') %}
        <div class="alert alert-warning">{{ message }}</div>
    {% endfor %}
    <h1>Prescription index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Date Prescription</th>
                <th>Medications</th>
                <th>Status Prescription</th>
                <th>Additional Notes</th>
                <th>Validity Duration</th>
                <th>Client Name</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for prescription in prescriptions %}
            <tr>
                <td>{{ prescription.id }}</td>
                <td>{{ prescription.datePrescription ? prescription.datePrescription|date('Y-m-d') : '' }}</td>
                <td>{{ prescription.medications }}</td>
                <td>{{ prescription.statusPrescription }}</td>
                <td>{{ prescription.additionalNotes }}</td>
                <td>{{ prescription.validityDuration }}</td>
                <td>{{ prescription.userCIN }}</td>
                <td>
                    <a href="{{ path('app_prescription_show', {'id': prescription.id}) }}" class="btn btn-primary">show</a>

                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <div class="text-center mt-4">
        <a href="{{ path('app_prescription_new') }}" class="btn btn-success">Create new</a>
    </div>
{% endblock %}

templates/prescription/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Prescription{% endblock %}

{% block body %}
    <h1>Create new Prescription</h1>

    {{ include('prescription/_form.html.twig') }}
    <a href="{{ path('app_prescription_index') }}" class="btn btn-secondary me-2">Back to list</a>
{% endblock %}

templates/prescription/pdf_template.html.twig
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Prescription PDF</title>
    <style>

        body {
            font-family: 'Open Sans', sans-serif;
            color: #444;
            background-color: #f4f4f4;
        }

        .container {
            width: 80%;
            margin: 0 auto;
            padding: 20px;
            background-color: #fff;
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }

        h1 {
            font-size: 32px;
            font-weight: 700;
            color: #333;
            margin-bottom: 20px;
        }

        p {
            font-size: 16px;
            line-height: 1.6;
            margin-bottom: 10px;
        }

        strong {
            font-weight: 700;
        }

        .footer {
            margin-top: 20px;
            text-align: center;
            font-size: 14px;
            color: #666;
        }
    </style>
</head>
<body>
<div class="container">
    <h1>Prescription</h1>
    <p><strong>Date:</strong> {{ prescription.datePrescription|date('Y-m-d') }}</p>
    <p><strong>Medications:</strong> {{ prescription.medications }}</p>
    <p><strong>Status:</strong> {{ prescription.statusPrescription }}</p>
    <p><strong>Additional Notes:</strong> {{ prescription.additionalNotes }}</p>
    <p><strong>Validity Duration:</strong> {{ prescription.validityDuration }}</p>
    <p><strong>User:</strong> {{ prescription.userCIN.firstName }}</p>
</div>
<div class="col-lg-3 col-md-6 footer-contact">
    <h3>Protechtini</h3>
    <p>
        18, rue de l'Usine <br>
        ZI Aéroport Charguia <br>
        II 2035 Ariana<br><br>
        <strong>Phone:</strong> (+216) 58 26 64 36 <br>
        <strong>Email:</strong> protechtini.synthcode@esprit.tn<br>
    </p>
</div>
</body>
</html>

templates/prescription/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Prescription{% endblock %}

{% block body %}
    {% if prescription is defined %}
    <h1>Prescription</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ prescription.id }}</td>
            </tr>
            <tr>
                <th>Date Prescription</th>
                <td>{{ prescription.datePrescription ? prescription.datePrescription|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Medications</th>
                <td>{{ prescription.medications }}</td>
            </tr>
            <tr>
                <th>Status Prescription</th>
                <td>{{ prescription.statusPrescription }}</td>
            </tr>
            <tr>
                <th>Additional Notes</th>
                <td>{{ prescription.additionalNotes }}</td>
            </tr>
            <tr>
                <th>Validity Duration</th>
                <td>{{ prescription.validityDuration }}</td>
            </tr>
            <tr>
                <th>Client Name</th>
                <td>{{prescription.userCIN }}</td>
            </tr>
        </tbody>
    </table>
    {% endif %}

    <div class="text-center mt-4">
        <form class="d-inline" action="{{ path('drug_search') }}" method="get">
            <label for="drugName" class="form-label">Search Medicine with OpenFDA:</label>
            <input type="text" id="drugName" name="drugName" placeholder="Enter medicine name" class="form-control d-inline-block" style="width: auto;">
            <button type="submit" class="btn btn-primary">Search</button>
        </form>
    </div>
    {% if drugDetails is defined %}
    <div class="mt-4">
        <h2>Drug Information:</h2>
        {# Example of displaying drug name and description. Adjust according to your API response structure #}
        <p><strong>Name:</strong> {{ drugDetails['openfda']['brand_name'][0] | default('Not Available') }}</p>
        <p><strong>Description:</strong> {{ drugDetails['description'][0] | default('Description not available') }}</p>
        {# Add more fields as needed #}
    </div>
{% endif %}

{% if prescription is defined %}
    <div class="mt-4 text-center">
        <a href="{{ path('app_prescription_index') }}" class="btn btn-secondary">Back to list</a>
        <a href="{{ path('app_prescription_edit', {'id': prescription.id}) }}" class="btn btn-warning">Edit</a>
        <a href="{{ path('prescription_export_pdf', {'id': prescription.id}) }}" class="btn btn-primary">Exporter en PDF</a>
    </div>
        <div class="mt-3 text-center">
            {{ include('prescription/_delete_form.html.twig') }}
        </div>
    {% endif %}
{% endblock %}