src/Entity/VehicleRequest.php
<?php

namespace App\Entity;

use App\Repository\VehicleRequestRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Doctrine\Common\Util\ClassUtils;
#[ORM\Entity(repositoryClass: VehicleRequestRepository::class)]
class VehicleRequest extends InsuranceRequest
{
    #[ORM\Column(length: 20)]
    #[Assert\NotBlank(message: 'Veuillez entrer la marque de votre vehicule')]

    private ?string $Marque = null;

    #[ORM\Column(length: 20)]
   #[Assert\NotBlank(message: 'Veuillez entrer le modele de votre vehicule.')]

    private ?string $Modele = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    #[Assert\NotBlank(message: 'Veuillez entrer la date de fabrication de votre vehicule.')]

    private ?\DateTimeInterface $Fab_year = null;

    #[ORM\Column(length: 20)]
       #[Assert\NotBlank(message: 'Veuillez entrer le numéro de serie de votre vehicule.')]
       #[Assert\Range(
           min: 1,
           max: 245,
           notInRangeMessage: 'Le numéro de série doit être compris entre {{ min }} et {{ max }}.'
       )]

    private ?string $serial_number = null;

    #[ORM\Column(length: 20)]
    #[Assert\Regex(
        pattern: '/^\d{1,3} TUN \d{1,4}$/',
        message: 'Le format de l\'immatriculation doit être : [Nombre entre 1 et 254] TUN [Nombre entre 1 et 9999].'
    )]
       #[Assert\NotBlank(message: "Veuillez entrer l'immatriculation de votre vehicule.")]

    private ?string $matricul_number = null;

    #[ORM\Column(length: 20)]
       #[Assert\NotBlank(message: 'Veuillez entrer la valeur de votre vehicule')]

    private ?string $vehicle_price = null;

    public function getMarque(): ?string
    {
        return $this->Marque;
    }

    public function setMarque(string $Marque): static
    {
        $this->Marque = $Marque;

        return $this;
    }

    public function getModele(): ?string
    {
        return $this->Modele;
    }

    public function setModele(string $Modele): static
    {
        $this->Modele = $Modele;

        return $this;
    }

    public function getFabYear(): ?\DateTimeInterface
    {
        return $this->Fab_year;
    }

    public function setFabYear(\DateTimeInterface $Fab_year): static
    {
        $this->Fab_year = $Fab_year;

        return $this;
    }

    public function getSerialNumber(): ?string
    {
        return $this->serial_number;
    }

    public function setSerialNumber(string $serial_number): static
    {
        $this->serial_number = $serial_number;

        return $this;
    }

    public function getMatriculNumber(): ?string
    {
        return $this->matricul_number;
    }

    public function setMatriculNumber(string $matricul_number): static
    {
        $this->matricul_number = $matricul_number;

        return $this;
    }

    public function getVehiclePrice(): ?string
    {
        return $this->vehicle_price;
    }

    public function setVehiclePrice(string $vehicle_price): static
    {
        $this->vehicle_price = $vehicle_price;

        return $this;
    }
}

src/Form/VehicleRequestType.php
<?php

namespace App\Form;
use App\Entity\User;

use App\Entity\VehicleRequest;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\TextType;

class VehicleRequestType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('dateRequest')
            ->add('typeInsurance', ChoiceType::class, [
                 'choices' => [
                     'Assurance véhicule' => 'vehicule',
                     'Assurance habitat' => 'habitat',
                     'Assurance vie' => 'vie',
                 ],
                 'placeholder' => 'Choisir le type de votre assurance',
             ])
            ->add('Marque', TextType::class, [
                                            'attr' => [
                                                'placeholder' => 'Entrez la marque de votre vehicule',
                                            ],
                                            ])
            ->add('Modele', TextType::class, [
                                          'attr' => [
                                              'placeholder' => 'Entrez le modele de votre vehicule',
                                          ],
                                          ])
            ->add('Fab_year')
            ->add('serial_number', TextType::class, [
                                                 'attr' => [
                                                     'placeholder' => 'Entrez le numéro de série de votre vehicule',
                                                ],
                                                                                           ])
            ->add('matricul_number', TextType::class, [
                                                   'attr' => [
                                                       'placeholder' => 'Entrez la matricule de votre vehicule',
                                                   ],
                                                                                              ])
            ->add('vehicle_price', TextType::class, [
                                                 'attr' => [
                                                     'placeholder' => "Entrez le prix d'achat de votre vehicule.",
                                                 ],
                                                                                            ])
                  ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => VehicleRequest::class,
        ]);
    }
}

src/Controller/VehicleRequestController.php
<?php

namespace App\Controller;
use App\Entity\User;

use App\Entity\VehicleRequest;
use App\Form\VehicleRequestType;
use App\Repository\VehicleRequestRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Entity\Notification;

#[Route('/vehicle/request')]
class VehicleRequestController extends AbstractController
{
    #[Route('/', name: 'app_vehicle_request_index', methods: ['GET'])]
    public function index(VehicleRequestRepository $vehicleRequestRepository): Response
    {
        return $this->render('vehicle_request/index.html.twig', [
            'vehicle_requests' => $vehicleRequestRepository->findAll(),
        ]);
    }

    #[Route('/new_VehicleRequest', name: 'app_vehicle_request_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $vehicleRequest = new VehicleRequest();
        $form = $this->createForm(VehicleRequestType::class, $vehicleRequest);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $vehicleRequest->setRequestUser($this->getUser());
            $entityManager->persist($vehicleRequest);
            $entityManager->flush();
            $notification = new Notification();
            $typeInsurance = $vehicleRequest->getTypeInsurance();
            $titre = 'Demande d\'assurance ' . $typeInsurance;
            $notification->setTitre($titre);
            $notification->setMessage('Une nouvelle demande d\'assurance a été ajoutée.');
            $notification->setDateNotification(date('Y-m-d H:i:s'));
            $entityManager->persist($notification);
            $entityManager->flush();
            return $this->redirectToRoute('app_vehicle_request_show_paruser', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('vehicle_request/new.html.twig', [
            'vehicle_request' => $vehicleRequest,
            'form' => $form,
        ]);
    }
    #[Route('/user/showv', name: 'app_vehicle_request_show_paruser', methods: ['GET'])]
    public function showParUser(VehicleRequestRepository $req): Response
    {
        $user=$this->getUser();
        if ($user instanceof User){
            // dd($user);
            $requ=$req->findBy(['requestUser'=>$user->getId()]);
            // $requests=$user->getRequests();
        }
        // dd($requ);
        return $this->render('vehicle_request/userRequest.html.twig', [
            'vehicle_requests' => $requ,
        ]);
    }

    #[Route('/{id}', name: 'app_vehicle_request_show', methods: ['GET'])]
    public function show(VehicleRequest $vehicleRequest): Response
    {
        return $this->render('vehicle_request/show.html.twig', [
            'vehicle_request' => $vehicleRequest,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_vehicle_request_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, VehicleRequest $vehicleRequest, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(VehicleRequestType::class, $vehicleRequest);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_vehicle_request_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('vehicle_request/edit.html.twig', [
            'vehicle_request' => $vehicleRequest,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_vehicle_request_delete', methods: ['POST'])]
    public function delete(Request $request, VehicleRequest $vehicleRequest, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$vehicleRequest->getId(), $request->request->get('_token'))) {

            $entityManager->remove($vehicleRequest);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_vehicle_request_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/vehicle_request/_delete_form.html.twig
<form id="deleteForm" method="post" action="{{ path('app_vehicle_request_delete', {'id': vehicle_request.id}) }}">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ vehicle_request.id) }}">
    <button type="button" id="deleteButton" class="btn btn-danger">Delete</button>
</form>
                  <script src="https://cdn.jsdelivr.net/npm/sweetalert2@10"></script>

  <script>
      document.getElementById('deleteButton').addEventListener('click', function(event) {
          event.preventDefault();

          Swal.fire({
              title: 'Are you sure?',
              text: "You won't be able to revert this!",
              icon: 'warning',
              showCancelButton: true,
              confirmButtonColor: '#3085d6',
              cancelButtonColor: '#d33',
              confirmButtonText: 'Yes, delete it!'
          }).then((result) => {
              if (result.isConfirmed) {
                  Swal.fire({
                      title: "Deleted!",
                      text: "Your file has been deleted.",
                      icon: "success"
                  });

                  document.getElementById('deleteForm').submit();
              }
          });
      });
  </script>

templates/vehicle_request/_form.html.twig
<body>
<main>
    <div class="container">
        <div class="row justify-content-center align-items-center min-vh-100">
            <div class="col-md-6">
                <img src="{{asset('FrontOffice/img/voiture.png')}}" class="img-fluid animated" alt="">
            </div>
            <div class="col-md-6">
                <section class="section register min-vh-100 d-flex flex-column align-items-center justify-content-center py-4">
                    <div class="card mb-3">
                        <div class="card-body">
                            {{ form_start(form, {'attr': {'class': 'row g-3 needs-validation', 'novalidate': 'novalidate', 'enctype': 'multipart/form-data'}}) }}
                            {% if form_errors(form) %}
                                <div class="alert alert-danger">
                                    <ul>
                                        {% for error in form_errors(form) %}
                                            <li>{{ error.message }}</li>
                                        {% endfor %}
                                    </ul>
                                </div>
                            {% endif %}
                            <div class="col-12">
                                <div class="step" id="step1">
                                    <div class="text-center mb-4">

                                        <h2>Informations de l'assuré</h2>
                                    </div>
                                    <div class="col-12">
                                        <label for="Date Demande" class="form-label">Date Demande</label>
                                        {{ form_widget(form.dateRequest, {'attr': {'class': 'form-control', 'id': 'dateRequest'}}) }}
                                    </div>
                                    <div class="col-12">
                                        <label for="typeInsurance" class="form-label">Type de l'assurance</label>
                                        {{ form_widget(form.typeInsurance, {'attr': {'class': 'form-control', 'id': 'typeInsurance'}}) }}
                                    </div>

                                   
                                    <button class="btn btn-primary w-100" type="button" onclick="nextStep('step1', 'step2')">Next <i class="bi bi-arrow-right-short"></i></button>
                                </div>
                            </div>

                            <div class="step" id="step2" style="display: none;">
                                <div class="col-12">
                                    <div class="text-center mb-4">

                                        <h2>Informations de l'habitat</h2>
                                    </div>
                                    <label for="Address" class="form-label">Marque</label>
                                    {{ form_widget(form.Marque, {'attr': {'class': 'form-control', 'id': 'Marque'}}) }}
                                    {% if form_errors(form.Marque) %}
                                        <div class="alert alert-danger">
                                            {{ form_errors(form.Marque) }}
                                        </div>
                                    {% endif %}
                                </div>
                                <div class="col-12">
                                    <label for="Modele" class="form-label">Modele</label>
                                    {{ form_widget(form.Modele, {'attr': {'class': 'form-control', 'id': 'Modele'}}) }}
                                    {% if form_errors(form.Modele) %}
                                        <div class="alert alert-danger">
                                            {{ form_errors(form.Modele) }}
                                        </div>
                                    {% endif %}
                                </div>
                                <div class="col-12">
                                    <label for="Fab_year" class="form-label">Fab_year</label>
                                    {{ form_widget(form.Fab_year, {'attr': {'class': 'form-control', 'id': 'Fab_year'}}) }}
                                    {% if form_errors(form.Fab_year) %}
                                        <div class="alert alert-danger">
                                            {{ form_errors(form.Fab_year) }}
                                        </div>
                                    {% endif %}
                                </div>
                                <div class="col-12">
                                    <label for="serial_number" class="form-label">serial_number</label>
                                    {{ form_widget(form.serial_number, {'attr': {'class': 'form-control', 'id': 'serial_number'}}) }}
                                    {% if form_errors(form.serial_number) %}
                                        <div class="alert alert-danger">
                                            {{ form_errors(form.serial_number) }}
                                        </div>
                                    {% endif %}
                                </div>
                                <div class="col-12">
                                    <label for="matricul_number" class="form-label">matricul_number</label>
                                    {{ form_widget(form.matricul_number, {'attr': {'class': 'form-control', 'id': 'matricul_number'}}) }}
                                    {% if form_errors(form.matricul_number) %}
                                        <div class="alert alert-danger">
                                            {{ form_errors(form.matricul_number) }}
                                        </div>
                                    {% endif %}
                                </div>
                                <div class="col-12">
                                    <label for="vehicle_price" class="form-label">vehicle_price</label>
                                    {{ form_widget(form.vehicle_price, {'attr': {'class': 'form-control', 'id': 'vehicle_price'}}) }}
                                    {% if form_errors(form.vehicle_price) %}
                                        <div class="alert alert-danger">
                                            {{ form_errors(form.vehicle_price) }}
                                        </div>
                                    {% endif %}
                                </div>
                                <div class="col-12">
                                    <div class="row">
                                        <div class="col">
                                            <button class="btn btn-primary w-100" type="button" onclick="prevStep('step2', 'step1')"> <i class="bi bi-arrow-left-short"></i>
                                                Previous</button>
                                        </div>
                                        <div class="col">
                                            <button class="btn btn-primary w-100" onclick="submitForm()">{{ button_label|default('Save') }} <i class="bi bi-check"></i>
                                            </button>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <!-- Add other fields related to vehicle A information here -->

                            <div class="col-12">
                                <a href="{{ path('app_vehicle_request_index') }}" class="btn btn-primary w-100">Back to List</a>
                            </div>

                            {{ form_end(form) }}

                        </div>
                    </div>
                </section>
            </div>
        </div>
</main><!-- End #main -->
</body>

<script>
    function showStep(stepId) {
        // Hide all steps
        document.getElementById('step1').style.display = 'none';
        document.getElementById('step2').style.display = 'none';
        // Show the specified step
        document.getElementById(stepId).style.display = 'block';
    }

    function nextStep(currentStepId, nextStepId) {
        // Add validation or logic here if needed before proceeding to the next step
        showStep(nextStepId);
    }

    function prevStep(currentStepId) {
        // Add validation or logic here if needed before going to the previous step
        if (currentStepId === 'step2') {
            showStep('step1');
        }
    }
</script>

templates/vehicle_request/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit VehicleRequest{% endblock %}

{% block body %}
<div class="section-title">

    <h2>Modifier une demande d'assurance</h2>
 </div>

    {{ include('vehicle_request/_form.html.twig', {'button_label': 'Update'}) }}


    {{ include('vehicle_request/_delete_form.html.twig') }}
{% endblock %}

templates/vehicle_request/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}VehicleRequest Index{% endblock %}

{% block body %}
<div class="container mt-5">
    <div class="section-title">
        <h2>Liste des assurances vehicules</h2>
    </div>
    <table class="table">
        <thead>
                <tr>
                    <th>Id</th>
                    <th>DateRequest</th>
                    <th>TypeInsurance</th>
                    <th>Status</th>
                    <th>Marque</th>
                    <th>Modele</th>
                    <th>Fab_year</th>
                    <th>Serial_number</th>
                    <th>Matricul_number</th>
                    <th>Vehicle_price</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                {% for vehicle_request in vehicle_requests %}
                    <tr>
                        <td>{{ vehicle_request.id }}</td>
                        <td>{{ vehicle_request.dateRequest ? vehicle_request.dateRequest|date('Y-m-d') : '' }}</td>
                        <td>{{ vehicle_request.typeInsurance }}</td>
                        <td class="{% if vehicle_request.status == 'Accepter' %}text-success{% elseif vehicle_request.status == 'Refusée' %}text-danger{% endif %}">{{ vehicle_request.status }}</td>
                        <td>{{ vehicle_request.Marque }}</td>
                        <td>{{ vehicle_request.Modele }}</td>
                        <td>{{ vehicle_request.FabYear ? vehicle_request.FabYear|date('Y-m-d') : '' }}</td>
                        <td>{{ vehicle_request.serialNumber }}</td>
                        <td>{{ vehicle_request.matriculNumber }}</td>
                        <td>{{ vehicle_request.vehiclePrice }}</td>
                        <td>
                            <a href="{{ path('app_vehicle_request_show', {'id': vehicle_request.id}) }}" class="btn btn-primary">Show</a>
                            <a href="{{ path('app_vehicle_request_edit', {'id': vehicle_request.id}) }}" class="btn btn-warning">Edit</a>
                        <a href="{{ path('app_contrat_vehicule_user') }}" class="btn btn-warning">Contrat</a>

                        </td>
                    </tr>
                {% else %}
                    <tr>
                        <td colspan="11">No records found</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>

        <a href="{{ path('app_vehicle_request_new') }}" class="btn btn-success">Create new</a>
    </div>
</div>
{% endblock %}

templates/vehicle_request/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New VehicleRequest{% endblock %}

{% block body %}
<div class="section-title">
    <h2>Demander une assurance vehicule</h2>
 </div>


    {{ include('vehicle_request/_form.html.twig') }}

{% endblock %}

templates/vehicle_request/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Demande vehicule {{ vehicle_request.id }}{% endblock %}

{% block body %}
 <div class="section-title">

    <h2>Demande vehicule {{ vehicle_request.id }}</h2>
</div>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ vehicle_request.id }}</td>
            </tr>
            <tr>
                <th>DateRequest</th>
                <td>{{ vehicle_request.dateRequest ? vehicle_request.dateRequest|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>TypeInsurance</th>
                <td>{{ vehicle_request.typeInsurance }}</td>
            </tr>
            <tr>
                <th>Status</th>
                <td>{{ vehicle_request.status }}</td>
            </tr>
            <tr>
                <th>Marque</th>
                <td>{{ vehicle_request.Marque }}</td>
            </tr>
            <tr>
                <th>Modele</th>
                <td>{{ vehicle_request.Modele }}</td>
            </tr>
            <tr>
                <th>Fab_year</th>
                <td>{{ vehicle_request.FabYear ? vehicle_request.FabYear|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Serial_number</th>
                <td>{{ vehicle_request.serialNumber }}</td>
            </tr>
            <tr>
                <th>Matricul_number</th>
                <td>{{ vehicle_request.matriculNumber }}</td>
            </tr>
            <tr>
                <th>Vehicle_price</th>
                <td>{{ vehicle_request.vehiclePrice }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_vehicle_request_index') }}">back to list</a>

    <a href="{{ path('app_vehicle_request_edit', {'id': vehicle_request.id}) }}">edit</a>

    {{ include('vehicle_request/_delete_form.html.twig') }}
{% endblock %}

templates/vehicle_request/showContrat.html.twig
{% extends 'client/index.html.twig' %}

{% block title %}ContratVehicule index{% endblock %}

{% block content %}
<div class="container mt-4">
<section>
    <div class="container mt-4">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title mb-4">Contrats Vehicule</h5>
                        <div class="d-flex justify-content-between align-items-center mb-3">
                            <div class="input-group" style="width: 40%;">
                                <input class="form-control border-end-0 border rounded-pill py-2" type="search" id="example-search-input" style="font-size: 0.875rem;" placeholder="Search...">
                                <span class="input-group-append">
                                    <button class="btn btn-outline-secondary border-bottom-0 border rounded-pill py-2" type="button" id="searchButton" style="font-size: 0.875rem;">Search</button>
                                </span>
                            </div>
                        </div>
                        <table class="table table-striped">
                            <thead>
                                <tr>
                                    <th>Id</th>
                                    <th>Date_debut</th>
                                    <th>Date_fin</th>
                                    <th>Description</th>
                                    <th>Prix</th>
                                    <th>MatriculeAgent</th>
                                    <th>Actions</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr class="requestVehicule-row">
                                    <td>{{ contrat_vehicule.id }}</td>
                                    <td>{{ contrat_vehicule.DateDebut ? contrat_vehicule.DateDebut|date('Y-m-d') : '' }}</td>
                                    <td>{{ contrat_vehicule.DateFin ? contrat_vehicule.DateFin|date('Y-m-d') : '' }}</td>
                                    <td>{{ contrat_vehicule.Description }}</td>
                                    <td>{{ contrat_vehicule.Prix }}</td>
                                    <td>{{ contrat_vehicule.MatriculeAgent }}</td>
                                    <td>
                                        <a href="{{ path('app_stripe') }}" class="btn btn-warning">
                                            <i class="bi bi-pencil-square"></i>
                                        </a>
                                    </td>
                                </tr>
                                <tr>
                                    <td colspan="7">No records found</td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>

<script>
    $(document).ready(function () {
        $('#searchButton').click(function () {
            var searchQuery = $('#example-search-input').val().toLowerCase();
            var noRequestVehiculeRow = $('#noUserRequestVehiculeRow');

            // Loop through each user row and show/hide based on the search query
            $('.requestVehicule-row').each(function () {
                var userRowText = $(this).text().toLowerCase();

                // If the search query is found in the user row, show it; otherwise, hide it
                $(this).toggle(userRowText.includes(searchQuery));
            });

            noRequestVehiculeRow.toggle($('.requestVehicule-row:visible').length === 0);
        });
    });
</script>
{% endblock %}

templates/vehicle_request/userRequest.html.twig
{% extends 'base.html.twig' %}

{% block title %}VehicleRequest Index{% endblock %}

{% block body %}
<div class="container mt-5">
    <div class="section-title">
        <h2>Liste des assurances vehicules</h2>
    </div>
    <table class="table">
        <thead>
                <tr>
                    <th>Id</th>
                    <th>DateRequest</th>
                    <th>TypeInsurance</th>
                    <th>Status</th>
                    <th>Marque</th>
                    <th>Modele</th>
                    <th>Fab_year</th>
                    <th>Serial_number</th>
                    <th>Matricul_number</th>
                    <th>Vehicle_price</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                {% for vehicle_request in vehicle_requests %}
                    <tr>
                        <td>{{ vehicle_request.id }}</td>
                        <td>{{ vehicle_request.dateRequest ? vehicle_request.dateRequest|date('Y-m-d') : '' }}</td>
                        <td>{{ vehicle_request.typeInsurance }}</td>
                        <td class="{% if vehicle_request.status == 'Accepter' %}text-success{% elseif vehicle_request.status == 'Refusée' %}text-danger{% endif %}">{{ vehicle_request.status }}</td>
                        <td>{{ vehicle_request.Marque }}</td>
                        <td>{{ vehicle_request.Modele }}</td>
                        <td>{{ vehicle_request.FabYear ? vehicle_request.FabYear|date('Y-m-d') : '' }}</td>
                        <td>{{ vehicle_request.serialNumber }}</td>
                        <td>{{ vehicle_request.matriculNumber }}</td>
                        <td>{{ vehicle_request.vehiclePrice }}</td>
                        <td>
                            <a href="{{ path('app_vehicle_request_show', {'id': vehicle_request.id}) }}" class="btn btn-primary">Show</a>
                            <a href="{{ path('app_vehicle_request_edit', {'id': vehicle_request.id}) }}" class="btn btn-warning">Edit</a>
                        </td>
                    </tr>
                {% else %}
                    <tr>
                        <td colspan="11">No records found</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>

        
    <a href="{{ path('app_vehicle_request_new') }}" class="btn btn-success">Create new</a>
   <br>
    <br>
</div>
</div>
{% endblock %}