src/Entity/Sinister.php
<?php

namespace App\Entity;

use App\Repository\SinisterRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: SinisterRepository::class)]
#[ORM\InheritanceType("JOINED")]
#[ORM\DiscriminatorColumn(name: "type", type: "string")]
#[ORM\DiscriminatorMap(array(
    "sinistreVehicule" => "SinisterVehicle",
    "sinistreProperty" => "SinisterProperty"
))]
abstract class Sinister
{
    public function __toString(): string
    {
        // Customize this method based on how you want to represent Sinister as a string
        return $this->getId() ? $this->getId().' - '.$this->getLocation().' - '.$this->getDateSinister()->format('Y-m-d') : 'New Sinister';
    }
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: "integer")]
    private ?int $id = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    #[Assert\NotBlank(message: "La date ne doit pas être vide.")]
    private ?\DateTimeInterface $dateSinister = null;
    

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: 'veuillez sélectionner la localisation')]
    private ?string $location = null;

    #[ORM\ManyToOne(inversedBy: 'sinisters')]
    private ?User $sinisterUser = null;


    #[ORM\Column(length: 255, nullable: true)]
    private ?string $status_sinister = 'en_cours';



    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDateSinister(): ?\DateTimeInterface
    {
        return $this->dateSinister;
    }
    

    public function setDateSinister(\DateTimeInterface $dateSinister): static
    {
        $this->dateSinister = $dateSinister;

        return $this;
    }

    public function getLocation(): ?string
    {
        return $this->location;
    }

    public function setLocation(string $location): static
    {
        $this->location = $location;

        return $this;
    }

    public function getSinisterUser(): ?User
    {
        return $this->sinisterUser;
    }

    public function setSinisterUser(?User $sinisterUser): static
    {
        $this->sinisterUser = $sinisterUser;

        return $this;
    }

   

    public function getStatusSinister(): ?string
    {
        return $this->status_sinister;
    }

    public function setStatusSinister(?string $status_sinister): static
    {
        $this->status_sinister = $status_sinister;

        return $this;
    }

  
}

src/Entity/SinisterProperty.php
<?php

namespace App\Entity;

use App\Repository\SinisterPropertyRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
#[ORM\Entity(repositoryClass: SinisterPropertyRepository::class)]
class SinisterProperty extends Sinister
{


    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: 'veuillez sélectionner le type de dégat')]
    private ?string $type_degat = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: 'veuillez introduire la description des décats survenues')]
    private ?string $description_degat = null;


    public function getTypeDegat(): ?string
    {
        return $this->type_degat;
    }

    public function setTypeDegat(string $type_degat): static
    {
        $this->type_degat = $type_degat;

        return $this;
    }

    public function getDescriptionDegat(): ?string
    {
        return $this->description_degat;
    }

    public function setDescriptionDegat(string $description_degat): static
    {
        $this->description_degat = $description_degat;

        return $this;
    }
}

src/Form/SinisterPropertyType.php
<?php

namespace App\Form;

use App\Entity\SinisterProperty;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Validator\Constraints\Date;
use Symfony\Component\Validator\Constraints\NotBlank;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use App\Entity\User;
class SinisterPropertyType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
      
        ->add('dateSinister')
        ->add('location')
        ->add('type_degat', ChoiceType::class, [
            'choices' => [
                'volé' => 'volé',
                'incendié' => 'incendié',
                'inondé' => 'inondé',
            ],
            'placeholder' => 'Sélectionnez un type de dégât', 
            
        ])
            ->add('description_degat', TextareaType::class, [
                'label' => 'Description du dégat',
               
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => SinisterProperty::class,
        ]);
    }
}

src/Controller/SinisterPropertyController.php
<?php

namespace App\Controller;

use App\Entity\SinisterProperty;
use App\Form\SinisterPropertyType;
use App\Repository\SinisterPropertyRepository;
use App\Entity\Rapport;
use App\Repository\SinisterRepository;
use App\Repository\RapportRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Entity\User;
use Knp\Component\Pager\PaginatorInterface;

#[Route('/sinister/property')]
class SinisterPropertyController extends AbstractController
{
    #[Route('/', name: 'app_sinister_property_index', methods: ['GET'])]
    public function index(PaginatorInterface $paginator , SinisterPropertyRepository $sinisterPropertyRepository, RapportRepository $rapportRepository, Request $request): Response
    {
        $pagination = $paginator->paginate(
            $sinisterPropertyRepository->findAll(),
            $request->query->getInt('page', 1), // Get the page number from the request
            5 // Number of items per page
        );
        return $this->render('sinister_property/index.html.twig', [
            'sinister_properties' =>   $pagination,
            'rapport' =>  $rapportRepository->findAll()
        ]);
    }
    #[Route('/user/show/sp', name: 'app_prop_show_paruser', methods: ['GET'])]
    public function showParUser(SinisterPropertyRepository $req): Response
    {
        $user=$this->getUser();
        if ($user instanceof User){
            // dd($user);
            $requ=$req->findBy(['sinisterUser'=>$user->getId()]);
            
        }
       
        return $this->render('sinister_property/userRequest.html.twig', [
            'sinister_properties' => $requ,
        ]);
    }
    
    #[Route('/usersinistre/{userId}', name: 'app_user_sinister', methods: ['GET', 'POST'])]

    public function sinistresByUser(SinisterRepository $sinistreRepository, $userId): Response
    {
        $sinistres = $sinistreRepository->findByUserId($userId);
        // Do something with the $sinistres, like passing it to a template or returning a JSON response.

        return $this->render('sinister_property/indexC.html.twig', [
            'sinister_properties' => $sinistres,
        ]);
    }
    #[Route('/new', name: 'app_sinister_property_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager, SinisterPropertyRepository $sinisterPropertyRepository): Response
    {
        // Fetch the user based on the static ID
        $user=$this->getUser();
        if ($user instanceof User) {
            $id=$user->getId();
        }
        $staticUserId = $id; // Replace with the actual static user ID
        $user = $this->getDoctrine()->getRepository(User::class)->find($staticUserId);

        if (!$user) {
            throw $this->createNotFoundException('User not found');
        }

        $sinisterProperty = new SinisterProperty();
        $sinisterProperty->setSinisterUser($user); // Associate the user with the SinisterProperty

        $form = $this->createForm(SinisterPropertyType::class, $sinisterProperty);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($sinisterProperty);
            $entityManager->flush();

            $message = "Votre déclaration de sinistre habitation a été enregistrée. Un expert la traitera et vous contactera pour plus d'informations.";
                $this-> addFlash('success',$message);
                return $this->redirectToRoute('app_prop_show_paruser', [], Response::HTTP_SEE_OTHER);
            // return $this->render('sinister_property/indexC.html.twig', [
            //     'message' => $message,
            //     'sinister_properties' => $sinisterPropertyRepository->findAll(),
            // ]);
        }

        return $this->renderForm('sinister_property/new.html.twig', [
            'sinister_property' => $sinisterProperty,
            'form' => $form,
        ]);
    }

    #[Route('/show/{id}', name: 'app_sinister_property_show', methods: ['GET'])]
    public function showAdmin(SinisterProperty $sinisterProperty): Response
    {
        return $this->render('sinister_property/show.html.twig', [
            'sinister_property' => $sinisterProperty,
        ]);
    }


    #[Route('/{id}', name: 'app_sinister_property_show_admin', methods: ['GET'])]
    public function show(SinisterProperty $sinisterProperty): Response
    {
        
        return $this->render('sinister_property/show_admin.html.twig', [
            'sinister_property' => $sinisterProperty,
          
        ]);
    }

    #[Route('/{id}/edit', name: 'app_sinister_property_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, SinisterProperty $sinisterProperty, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(SinisterPropertyType::class, $sinisterProperty);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

           
            $message = "Votre modification a été enregistrée. Un expert la traitera et vous contactera pour plus d'informations.";
            $this-> addFlash('success',$message);
         
            return $this->redirectToRoute('app_prop_show_paruser', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('sinister_property/edit.html.twig', [
            'sinister_property' => $sinisterProperty,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_sinister_property_delete', methods: ['POST'])]
    public function delete(Request $request, SinisterProperty $sinisterProperty, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$sinisterProperty->getId(), $request->request->get('_token'))) {
            $entityManager->remove($sinisterProperty);
            $entityManager->flush();
            $message = "Votre sinistre a été supprimé. ";
    

            $this-> addFlash('success',$message);
         
            return $this->redirectToRoute('app_prop_show_paruser', [], Response::HTTP_SEE_OTHER);
        }

        
        }

       
    }

templates/sinister_property/_delete_form.html.twig
<form method="post" action="{{ path('app_sinister_property_delete', {'id': sinister_property.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ sinister_property.id) }}">
    <button class="btn btn-danger mt3">Delete</button>
</form>

templates/sinister_property/_form.html.twig
<body>
  <main>
    <div class="container">
<!-- Add this script tag to include jQuery -->
<script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>


      <section class="section register min-vh-100 d-flex flex-column align-items-center justify-content-center py-4">
<div class="card mb-3">

                <div class="card-body">


{{ form_start(form, {'attr': {'class': 'row g-3 needs-validation', 'novalidate': 'novalidate', 'enctype': 'multipart/form-data'}}) }}
            {% if form_errors(form) %}

            <div class="alert alert-danger">
                <ul>
                    {% for error in form_errors(form) %}
                        <li>{{ error.message }}</li>
                    {% endfor %}
                </ul>
            </div>
        {% endif %}
   <div class="col-12">
              
                <h2>Informations à propos l'accident</h2>
                              <label for="dateSinister" class="form-label">Date Sinister</label>
              {{ form_widget(form.dateSinister) }}
              {% if form_errors(form.dateSinister) %}
                <div class="alert alert-danger">
                  {{ form_errors(form.dateSinister) }}
                </div>
              {% endif %}
                  <div class="col-12">
                <label for="location" class="form-label">Location</label>
                {{ form_widget(form.location, {'attr': {'class': 'form-control', 'id': 'location'}}) }}
                                {% if form_errors(form.location) %}
                       <div class="alert alert-danger">
                           {{ form_errors(form.location) }}
                       </div>
            {% endif %}
                               <div class="col-12">
                <label for="location" class="form-label">Type de dégat</label>
                {{ form_widget(form.type_degat, {'attr': {'class': 'form-control', 'id': 'type_degat'}}) }}
                                {% if form_errors(form.type_degat) %}
                       <div class="alert alert-danger">
                           {{ form_errors(form.type_degat) }}
                       </div>
            {% endif %}
                                       <div class="col-12">
                <label for="location" class="form-label">Description des dégats</label>
               {{ form_widget(form.description_degat, {'attr': {'class': 'form-control', 'id': 'description_degat', 'rows':10}}) }}

                                {% if form_errors(form.description_degat) %}
                       <div class="alert alert-danger">
                           {{ form_errors(form.description_degat) }}
                       </div>
            {% endif %}

    

    <div class="col-12">

    <button class="btn btn-primary w-100">{{ button_label|default('Save') }}</button>
    </div>



{{ form_end(form) }}
</div>

</div>
      </section>

    </div>
  </main><!-- End #main -->



</body>

templates/sinister_property/del.html.twig
{% extends 'base.html.twig' %}

{% block title %}Success{% endblock %}

{% block stylesheets %}
    {# Include your custom CSS styles here #}
    <style>
        body {
            font-family: 'Arial', sans-serif;
            background-color: #f4f4f4;
            color: #333;
            margin: 0;
            padding: 0;
            display: flex;
            align-items: center;
            justify-content: center;
            height: 100vh;
        }

        .container {
            text-align: center;
            background-color: #fff;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }

        h1 {
            font-size: 36px;
            color: #007bff;
            margin-bottom: 20px;
        }

        p {
            font-size: 18px;
            line-height: 1.6;
            margin-bottom: 20px;
        }

        .button-container {
            display: flex;
            justify-content: center;
        }

        a {
            display: inline-block;
            padding: 10px 20px;
            margin: 0 10px;
            text-decoration: none;
            color: #fff;
            background-color: #007bff;
            border-radius: 4px;
            transition: background-color 0.3s;
        }

        a:hover {
            background-color: #0056b3;
        }
    </style>
{% endblock %}

{% block body %}
    <div class="container">
        <h1>Success!</h1>
        <p>{{ message }}</p>

     
    </div>
{% endblock %}

templates/sinister_property/details.html.twig
{% extends 'admin/index.html.twig' %}

{% block title %}SinisterProperty{% endblock %}

{% block profile %}
    <h1>SinisterProperty</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ sinister.id }}</td>
            </tr>
            <tr>
                <th>Type_degat</th>
                <td>{{ sinister.typeDegat }}</td>
            </tr>
            <tr>
                <th>Description_degat</th>
                <td>{{ sinister.descriptionDegat }}</td>
            </tr>
            <tr>
                <th>Status</th>
                <td>{{ sinister.statusSinister }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_sinister_property_edit', {'id': sinister.id}) }}">traiter</a>
{% endblock %}

templates/sinister_property/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit SinisterProperty{% endblock %}

{% block body %}
    <h1>Edit SinisterProperty</h1>

    {{ include('sinister_property/_form.html.twig', {'button_label': 'Update'}) }}

   

    {{ include('sinister_property/_delete_form.html.twig') }}
{% endblock %}

templates/sinister_property/index.html.twig
{% extends 'admin/index.html.twig' %}

{% block title %}Liste Des Sinistres Habitation{% endblock %}

{% block profile %}
  <h1>Liste Des Sinistres Habitation</h1>

    <div>
        <label for="orderByDate">Filtrer par Date:</label>
        <select id="orderByDate">
            <option value="all">Tous</option>
            <option value="asc">Date croissante</option>
            <option value="desc">Date décroissante</option>
        </select>
    </div>

    <div>
        <label for="filterByStatus">Filtrer par Status:</label>
        <select id="filterByStatus">
            <option value="">Tous</option>
            <option value="en_cours">En Cours</option>
            <option value="traité">Traité</option>
        </select>
    </div>

    <div>
        <label for="filterByDamageType">Filtrer par Type de Dégât:</label>
        <select id="filterByDamageType">
            <option value="all">Tous</option>
            <option value="volé">volé</option>
            <option value="incendié">incendié</option>
            <option value="inondé">inondé</option>
        </select>
  </div>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Date</th>
                <th>Type_degat</th>
                <th>Status</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody id="sinisterTableBody">
            {% for sinister_property in sinister_properties %}
                  <tr>
                    <td>{{ sinister_property.id }}</td>
                    <td>{{ sinister_property.dateSinister ? sinister_property.dateSinister|date('Y-m-d') : '' }}</td>
                    <td>{{ sinister_property.typeDegat }}</td>
                    <td style="color: {% if sinister_property.StatusSinister == 'traité' %}green{% elseif sinister_property.StatusSinister == 'en_cours' %}orange{% endif %}">
                        {{ sinister_property.StatusSinister }}
                    </td>
                    <td>
                        <a class="btn btn-success" href="{{ path('app_sinister_property_show_admin', {'id': sinister_property.id}) }}">show</a>
                        {% if sinister_property.StatusSinister == 'en_cours' %}
                            <a class="btn btn-warning" href="{{ path('app_rapport_new', {'id': sinister_property.id })}}">traiter</a>
                        {% elseif sinister_property.StatusSinister == 'traité' %}
                      

                        {% endif %}
                    </td>
                </tr>
            {% else %}
                <tr>
                    <td colspan="5">no records found</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    <nav aria-label="Page navigation example">
        <ul class="pagination " style="float: right;">
            {{ knp_pagination_render(sinister_properties) }}
        </ul>
    </nav>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

    <script>
        $(document).ready(function() {
            // Function to filter sinisters by order, status, and damage type
            $("#orderByDate, #filterByStatus, #filterByDamageType").on("change", function() {
                var order = $("#orderByDate").val();
                var selectedStatus = $("#filterByStatus").val();
                var selectedDamageType = $("#filterByDamageType").val();
                filterSinisters(order, selectedStatus, selectedDamageType);
            });

            function filterSinisters(order, selectedStatus, selectedDamageType) {
                $("#sinisterTableBody tr").sort(function(a, b) {
                    var dateA = new Date($(a).find("td:eq(1)").text()); 
                    var dateB = new Date($(b).find("td:eq(1)").text());

                    if (order === "all") {
                        return 0; // Don't change order
                    }

                    return order === "asc" ? dateA - dateB : dateB - dateA;
                }).each(function() {
                    var rowStatus = $(this).find("td:eq(3)").text(); 
                    var rowDamageType = $(this).find("td:eq(2)").text(); 
                    if (
                        (selectedStatus === "" || rowStatus === selectedStatus) &&
                        (selectedDamageType === "all" || rowDamageType === selectedDamageType)
                    ) {
                        $(this).show();
                    } else {
                        $(this).hide();
                    }
                }).appendTo("#sinisterTableBody");
            }

            // Function to color decisions
            $("#sinisterTableBody tr").each(function() {
                var rowStatus = $(this).find("td:eq(3)").text(); 
                if (rowStatus === "traité") {
                    $(this).find("td:eq(3)").css("color", "green");
                } else if (rowStatus === "en_cours") {
                    $(this).find("td:eq(3)").css("color", "orange");
                }
            });
        });
    </script>
{% endblock %}

templates/sinister_property/indexC.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste Des Sinistres Habitation{% endblock %}

{% block body %}
    <h1>Liste Des Sinistres Habitation</h1>
    
    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Date</th>
                <th>Type_degat</th>
                <th>Status</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for label, messages in app.flashes %}
        {% for message in messages %}
            <div class="alert alert-{{ label }} alert-dismissible fade show" role="alert">
                {{ message|raw }}
                <button type="button" class="btn-close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        {% endfor %}
    {% endfor %}
            {% for sinister_property in sinister_properties %}
                <tr>
                    <td>{{ sinister_property.id }}</td>
                    <td>{{ sinister_property.dateSinister ? sinister_property.dateSinister|date('Y-m-d') : '' }}</td>
                    <td>{{ sinister_property.typeDegat }}</td>
                    <td>{{ sinister_property.StatusSinister }}</td>
                    <td>
                        <a href="{{ path('app_sinister_property_show', {'id': sinister_property.id}) }}">show</a>
                    </td>
                </tr>
            {% else %}
                <tr>
                    <td colspan="5">no records found</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js"></script>

    
{% endblock %}

templates/sinister_property/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New SinisterProperty{% endblock %}

{% block body %}
<h1 class="text-center">Déclarer votre sinistre véhicule</h1>

    {{ include('sinister_property/_form.html.twig') }}


{% endblock %}

templates/sinister_property/new_success.html.twig
{% extends 'base.html.twig' %}

{% block title %}Success{% endblock %}

{% block stylesheets %}
    {# Include your custom CSS styles here #}
    <style>
        body {
            font-family: 'Arial', sans-serif;
            background-color: #f4f4f4;
            color: #333;
            margin: 0;
            padding: 0;
            display: flex;
            align-items: center;
            justify-content: center;
            height: 100vh;
        }

        .container {
            text-align: center;
            background-color: #fff;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }

        h1 {
            font-size: 36px;
            color: #007bff;
            margin-bottom: 20px;
        }

        p {
            font-size: 18px;
            line-height: 1.6;
            margin-bottom: 20px;
        }

        .button-container {
            display: flex;
            justify-content: center;
        }

        a {
            display: inline-block;
            padding: 10px 20px;
            margin: 0 10px;
            text-decoration: none;
            color: #fff;
            background-color: #007bff;
            border-radius: 4px;
            transition: background-color 0.3s;
        }

        a:hover {
            background-color: #0056b3;
        }
    </style>
{% endblock %}

{% block body %}
    <div class="container">
        <h1>Success!</h1>
        <p>{{ message }}</p>

        <div class="button-container">
            <a href="{{ path('app_sinister_property_show', {'id': sinister_property.id}) }}">Show</a>
            <a href="{{ path('app_sinister_property_edit', {'id': sinister_property.id}) }}">Edit</a>
            {# Add the delete button or any other actions as needed #}
        </div>
    </div>
{% endblock %}

templates/sinister_property/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}SinisterProperty{% endblock %}

{% block body %}
    <h1>SinisterProperty</h1>

        <table class="table table-bordered table-hover" >
        <tbody>
          
            <tr>
                <th>Type_degat</th>
                <td>{{ sinister_property.typeDegat }}</td>
            </tr>
            <tr>
                <th>Description_degat</th>
                <td>{{ sinister_property.descriptionDegat }}</td>
            </tr>
             <tr>
                <th>Status</th>
                <td>{{ sinister_property.StatusSinister }}</td>
            </tr>
        </tbody>
    </table>

{% if sinister_property.StatusSinister == 'traité' %}
        <a href="{{ path('app_rapport_showhh', {'id': sinister_property.id}) }}" class="btn btn-primary">Voir Rapport</a>
    {% endif %}

    {% if sinister_property.StatusSinister == 'en_cours' %}
<a class="btn btn-primary mt3" href="{{ path('app_sinister_property_edit', {'id': sinister_property.id}) }}">edit</a>
{{ include('sinister_property/_delete_form.html.twig') }}
{% endif %}
    

    
{% endblock %}

templates/sinister_property/show_admin.html.twig
{% extends 'admin/index.html.twig' %}

{% block title %}SinisterProperty{% endblock %}

{% block profile %}
    <h1>SinisterProperty</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ sinister_property.id }}</td>
            </tr>
            <tr>
                <th>Type_degat</th>
                <td>{{ sinister_property.typeDegat }}</td>
            </tr>
            <tr>
                <th>Description_degat</th>
                <td>{{ sinister_property.descriptionDegat }}</td>
            </tr>
            <tr>
                <th>Status</th>
                <td style="color: {% if sinister_property.StatusSinister == 'traité' %}green{% elseif sinister_property.StatusSinister == 'en_cours' %}orange{% endif %}">
                    {{ sinister_property.StatusSinister }}
                </td>
            </tr>
            
        </tbody>
    </table>
{% endblock %}

templates/sinister_property/userRequest.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste Des Sinistres Habitation{% endblock %}

{% block body %}
<div class="d-flex" >
<div class="col-md-12">
    <h1>Liste Des Sinistres Habitation</h1>
    
        <table class="table table-bordered table-hover" >
        <thead class="table-secondary">
       
            <tr>
                <th>Id</th>
                <th>Date</th>
                <th>Type_degat</th>
                <th>Status</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for label, messages in app.flashes %}
        {% for message in messages %}
            <div class="alert alert-{{ label }} alert-dismissible fade show" role="alert">
                {{ message|raw }}
                <button type="button" class="btn-close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        {% endfor %}
    {% endfor %}
            {% for sinister_property in sinister_properties %}
                <tr>
                    <td>{{ sinister_property.id }}</td>
                    <td>{{ sinister_property.dateSinister ? sinister_property.dateSinister|date('Y-m-d') : '' }}</td>
                    <td>{{ sinister_property.typeDegat }}</td>
                    <td>{{ sinister_property.StatusSinister }}</td>
                    <td>
                        <a class="btn btn-success mt3" href="{{ path('app_sinister_property_show', {'id': sinister_property.id}) }}">show</a>
                    </td>
                </tr>
            {% else %}
                <tr>
                    <td colspan="5">no records found</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js"></script>

    
{% endblock %}